/*
 * APIMATICCalculator.UWP
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 03/03/2017
 */
using System;
using APIMATICCalculator.UWP.Controllers;
using APIMATIC.SDK.Http.Client;

namespace APIMATICCalculator.UWP
{
    public partial class APIMATICCalculatorClient: IAPIMATICCalculatorClient
    {

        /// <summary>
        /// Singleton access to SimpleCalculator controller
        /// </summary>
        public ISimpleCalculatorController SimpleCalculator
        {
            get
            {
                return SimpleCalculatorController.Instance;
            }
        }
        /// <summary>
        /// The shared http client to use for all API calls
        /// </summary>
        public IHttpClient SharedHttpClient
        {
            get
            {
                return BaseController.ClientInstance;
            }
            set
            {
                BaseController.ClientInstance = value;
            }        
        }
        
        /// <summary>
        /// Default constructor
        /// </summary>
        public APIMATICCalculatorClient() { }

        /// <summary>
        /// Client initialization constructor
        /// </summary>
        public APIMATICCalculatorClient(string runscopeBucketKey, string oAuthAccessToken)
        {
            Configuration.RunscopeBucketKey = runscopeBucketKey;
            Configuration.OAuthAccessToken = oAuthAccessToken;
        }
    }
}