/*
 * APIMATICCalculator.UWP
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 03/03/2017
 */
using System;
using APIMATICCalculator.UWP.Controllers;

namespace APIMATICCalculator.UWP
{
    public partial interface IAPIMATICCalculatorClient
    {

        /// <summary>
        /// Singleton access to SimpleCalculator controller
        /// </summary>
        ISimpleCalculatorController SimpleCalculator { get;}

    }
}