/*
 * APIMATICCalculator.Tests
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Threading.Tasks;
using Newtonsoft.Json.Converters;
using APIMATIC.SDK.Common; 
using APIMATIC.SDK.Http.Client;
using APIMATIC.SDK.Http.Response;
using APIMATICCalculator.Tests.Helpers;
using Microsoft.VisualStudio.TestPlatform.UnitTestFramework;
using APIMATICCalculator.UWP;
using APIMATICCalculator.UWP.Controllers;
using APIMATICCalculator.UWP.Models;

namespace APIMATICCalculator.Tests
{
    [TestClass]
    public class SimpleCalculatorControllerTest : ControllerTestBase
    {
        /// <summary>
        /// Controller instance (for all tests)
        /// </summary>
        private static ISimpleCalculatorController controller;

        /// <summary>
        /// Setup test class
        /// </summary>
        [TestInitialize]
        public void SetUpClass()
        {
            controller = GetClient().SimpleCalculator;
            applyConfiguration();
        }

        /// <summary>
        /// Check if multiplication works 
        /// </summary>
        [TestMethod]
        public async Task TestMultiply() 
        {
            // Parameters for the API call
            GetCalculateInput input = new GetCalculateInput();
            input.Operation = OperationTypeEnumHelper.ParseString("MULTIPLY");
            input.X = 4;
            input.Y = 5;

            // Perform API call
            double? result = null;

            try
            {
                result = await controller.GetCalculateAsync(input);
            }
            catch(APIException) {};

            // Test response code
            Assert.AreEqual(200, httpCallBackHandler.Response.StatusCode,
                    "Status should be 200");

            // Test whether the captured response is as we expected
            Assert.IsNotNull(result, "Result should exist");

 
            Assert.AreEqual(
                    20, result,
                    "Response should match expected value");
        }

    }
}