/*
 * APIMATICCalculator.UWP
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 03/03/2017
 */
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using APIMATIC.SDK.Common;
using APIMATIC.SDK.Http.Request;
using APIMATIC.SDK.Http.Response;
using APIMATIC.SDK.Http.Client;
using APIMATICCalculator.UWP.Models;

namespace APIMATICCalculator.UWP.Controllers
{
    public partial interface ISimpleCalculatorController
    {
        /// <summary>
        /// Calculates the expression using the specified operation.
        /// </summary>
        /// <param name="GetCalculateInput">Object containing request parameters</param>
        /// <return>Returns the double? response from the API call</return>
        double? GetCalculate(GetCalculateInput input);

        /// <summary>
        /// Calculates the expression using the specified operation.
        /// </summary>
        /// <param name="GetCalculateInput">Object containing request parameters</param>
        /// <return>Returns the double? response from the API call</return>
        Task<double?> GetCalculateAsync(GetCalculateInput input);

    }
} 